// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: Helix Control panel 3

#include "../ui.h"

void ui_SCREENmain_screen_init(void)
{
    ui_SCREENmain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SCREENmain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SCREENmain, &ui_img_hex_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTDownTemp = lv_imgbtn_create(ui_SCREENmain);
    lv_imgbtn_set_src(ui_BTDownTemp, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_tdrelased_png, NULL);
    lv_imgbtn_set_src(ui_BTDownTemp, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_tdpressed_png, NULL);
    lv_obj_set_width(ui_BTDownTemp, 41);
    lv_obj_set_height(ui_BTDownTemp, lv_pct(100));
    lv_obj_set_style_opa(ui_BTDownTemp, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTUpTemp = lv_imgbtn_create(ui_SCREENmain);
    lv_imgbtn_set_src(ui_BTUpTemp, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_turelased_png, NULL);
    lv_imgbtn_set_src(ui_BTUpTemp, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_tupressed_png, NULL);
    lv_obj_set_width(ui_BTUpTemp, 41);
    lv_obj_set_height(ui_BTUpTemp, lv_pct(100));
    lv_obj_set_align(ui_BTUpTemp, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_opa(ui_BTUpTemp, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABTime = lv_label_create(ui_SCREENmain);
    lv_obj_set_width(ui_LABTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LABTime, 3);
    lv_obj_set_x(ui_LABTime, lv_pct(0));
    lv_obj_set_align(ui_LABTime, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LABTime, "Sabato 16 Marzo 2024 - 10:10");
    lv_label_set_recolor(ui_LABTime, "true");
    lv_obj_set_style_text_color(ui_LABTime, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABTime, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABRoomTemp = lv_label_create(ui_SCREENmain);
    lv_obj_set_width(ui_LABRoomTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABRoomTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABRoomTemp, lv_pct(0));
    lv_obj_set_y(ui_LABRoomTemp, lv_pct(30));
    lv_obj_set_align(ui_LABRoomTemp, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LABRoomTemp, "18°");
    lv_obj_set_style_text_color(ui_LABRoomTemp, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABRoomTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABRoomTemp, &ui_font_NebulaBIG, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABRoomSetpoint = lv_label_create(ui_SCREENmain);
    lv_obj_set_width(ui_LABRoomSetpoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABRoomSetpoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABRoomSetpoint, 0);
    lv_obj_set_y(ui_LABRoomSetpoint, 125);
    lv_obj_set_align(ui_LABRoomSetpoint, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LABRoomSetpoint, "Setpoint: 20°");
    lv_obj_set_style_text_color(ui_LABRoomSetpoint, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABRoomSetpoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABRoomSetpoint, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABRoomHum = lv_label_create(ui_SCREENmain);
    lv_obj_set_width(ui_LABRoomHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABRoomHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABRoomHum, 0);
    lv_obj_set_y(ui_LABRoomHum, 155);
    lv_obj_set_align(ui_LABRoomHum, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LABRoomHum, "RH 30%");
    lv_obj_set_style_text_color(ui_LABRoomHum, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABRoomHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABRoomHum, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABIndicators = lv_label_create(ui_SCREENmain);
    lv_obj_set_width(ui_LABIndicators, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABIndicators, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABIndicators, 0);
    lv_obj_set_y(ui_LABIndicators, -3);
    lv_obj_set_align(ui_LABIndicators, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LABIndicators, "LV_SYMBOL_SD_CARD");
    lv_label_set_recolor(ui_LABIndicators, "true");
    lv_obj_set_style_text_color(ui_LABIndicators, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABIndicators, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SCREENmain, ui_event_SCREENmain, LV_EVENT_ALL, NULL);

}
