// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: Helix Control panel 3

#include "../ui.h"

void ui_SCREENConnections_screen_init(void)
{
    ui_SCREENConnections = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SCREENConnections, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SCREENConnections, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SCREENConnections, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PANELConnection = lv_obj_create(ui_SCREENConnections);
    lv_obj_set_width(ui_PANELConnection, lv_pct(96));
    lv_obj_set_height(ui_PANELConnection, lv_pct(73));
    lv_obj_set_x(ui_PANELConnection, lv_pct(0));
    lv_obj_set_y(ui_PANELConnection, lv_pct(12));
    lv_obj_set_align(ui_PANELConnection, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PANELConnection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PANELConnection, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PANELConnection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PANELConnection, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PANELConnection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IPLab = lv_label_create(ui_PANELConnection);
    lv_obj_set_width(ui_IPLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPLab, lv_pct(26));
    lv_obj_set_y(ui_IPLab, lv_pct(5));
    lv_label_set_text(ui_IPLab, "...");
    lv_label_set_recolor(ui_IPLab, "true");
    lv_obj_set_style_text_color(ui_IPLab, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IPLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IPLab, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QR = lv_qrcode_create(ui_PANELConnection, 100, lv_color_hex3(0x33f), lv_color_hex3(0xeef));
    lv_obj_set_width(ui_QR, 100);
    lv_obj_set_height(ui_QR, 100);
    lv_obj_set_x(ui_QR, lv_pct(-2));
    lv_obj_set_y(ui_QR, lv_pct(-6));
    lv_obj_add_flag(ui_QR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_QR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SWAccessPoint = lv_switch_create(ui_PANELConnection);
    lv_obj_set_width(ui_SWAccessPoint, 125);
    lv_obj_set_height(ui_SWAccessPoint, 25);
    lv_obj_set_x(ui_SWAccessPoint, lv_pct(8));
    lv_obj_set_y(ui_SWAccessPoint, lv_pct(3));
    lv_obj_set_align(ui_SWAccessPoint, LV_ALIGN_BOTTOM_MID);


    ui_LABAccessPoint = lv_label_create(ui_PANELConnection);
    lv_obj_set_width(ui_LABAccessPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABAccessPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABAccessPoint, lv_pct(-1));
    lv_obj_set_y(ui_LABAccessPoint, lv_pct(0));
    lv_obj_set_align(ui_LABAccessPoint, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LABAccessPoint, "Access point Mode");
    lv_obj_set_style_text_color(ui_LABAccessPoint, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABAccessPoint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABAccessPoint, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABConnectionDesc = lv_label_create(ui_SCREENConnections);
    lv_obj_set_width(ui_LABConnectionDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABConnectionDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABConnectionDesc, lv_pct(3));
    lv_obj_set_y(ui_LABConnectionDesc, lv_pct(2));
    lv_label_set_text(ui_LABConnectionDesc, "Connections");
    lv_obj_set_style_text_color(ui_LABConnectionDesc, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABConnectionDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABConnectionDesc, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABConnVer = lv_label_create(ui_SCREENConnections);
    lv_obj_set_width(ui_LABConnVer, lv_pct(94));
    lv_obj_set_height(ui_LABConnVer, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_LABConnVer, lv_pct(3));
    lv_obj_set_y(ui_LABConnVer, lv_pct(-2));
    lv_obj_set_align(ui_LABConnVer, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_LABConnVer, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LABConnVer, "Software Version 1.0");
    lv_obj_set_style_text_color(ui_LABConnVer, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABConnVer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABConnVer, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SCREENConnections, ui_event_SCREENConnections, LV_EVENT_ALL, NULL);

}
