// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: Helix Control panel 3

#include "../ui.h"

void ui_SCREENSettings_screen_init(void)
{
    ui_SCREENSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SCREENSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SCREENSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SCREENSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PANELSettings = lv_obj_create(ui_SCREENSettings);
    lv_obj_set_width(ui_PANELSettings, lv_pct(96));
    lv_obj_set_height(ui_PANELSettings, lv_pct(77));
    lv_obj_set_x(ui_PANELSettings, lv_pct(0));
    lv_obj_set_y(ui_PANELSettings, lv_pct(12));
    lv_obj_set_align(ui_PANELSettings, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PANELSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PANELSettings, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PANELSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PANELSettings, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PANELSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SWWebFileManager = lv_switch_create(ui_PANELSettings);
    lv_obj_set_width(ui_SWWebFileManager, 125);
    lv_obj_set_height(ui_SWWebFileManager, 25);
    lv_obj_set_x(ui_SWWebFileManager, lv_pct(15));
    lv_obj_set_y(ui_SWWebFileManager, lv_pct(-89));
    lv_obj_set_align(ui_SWWebFileManager, LV_ALIGN_BOTTOM_MID);


    ui_LABWebFileManager = lv_label_create(ui_PANELSettings);
    lv_obj_set_width(ui_LABWebFileManager, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABWebFileManager, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABWebFileManager, lv_pct(-1));
    lv_obj_set_y(ui_LABWebFileManager, lv_pct(-92));
    lv_obj_set_align(ui_LABWebFileManager, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LABWebFileManager, "Web file manager");
    lv_obj_set_style_text_color(ui_LABWebFileManager, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABWebFileManager, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABWebFileManager, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SWWebAdvSettings = lv_switch_create(ui_PANELSettings);
    lv_obj_set_width(ui_SWWebAdvSettings, 125);
    lv_obj_set_height(ui_SWWebAdvSettings, 25);
    lv_obj_set_x(ui_SWWebAdvSettings, lv_pct(15));
    lv_obj_set_y(ui_SWWebAdvSettings, lv_pct(-58));
    lv_obj_set_align(ui_SWWebAdvSettings, LV_ALIGN_BOTTOM_MID);


    ui_LABWebAdvSettings = lv_label_create(ui_PANELSettings);
    lv_obj_set_width(ui_LABWebAdvSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABWebAdvSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABWebAdvSettings, lv_pct(-1));
    lv_obj_set_y(ui_LABWebAdvSettings, lv_pct(-60));
    lv_obj_set_align(ui_LABWebAdvSettings, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LABWebAdvSettings, "Web advanced settings");
    lv_obj_set_style_text_color(ui_LABWebAdvSettings, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABWebAdvSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABWebAdvSettings, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SWWebTerminal = lv_switch_create(ui_PANELSettings);
    lv_obj_set_width(ui_SWWebTerminal, 125);
    lv_obj_set_height(ui_SWWebTerminal, 25);
    lv_obj_set_x(ui_SWWebTerminal, lv_pct(15));
    lv_obj_set_y(ui_SWWebTerminal, lv_pct(-27));
    lv_obj_set_align(ui_SWWebTerminal, LV_ALIGN_BOTTOM_MID);


    ui_LABWebTerminal = lv_label_create(ui_PANELSettings);
    lv_obj_set_width(ui_LABWebTerminal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABWebTerminal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABWebTerminal, lv_pct(-1));
    lv_obj_set_y(ui_LABWebTerminal, lv_pct(-28));
    lv_obj_set_align(ui_LABWebTerminal, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LABWebTerminal, "Web Terminal");
    lv_obj_set_style_text_color(ui_LABWebTerminal, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABWebTerminal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABWebTerminal, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABSettingsDesc = lv_label_create(ui_SCREENSettings);
    lv_obj_set_width(ui_LABSettingsDesc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABSettingsDesc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LABSettingsDesc, lv_pct(3));
    lv_obj_set_y(ui_LABSettingsDesc, lv_pct(2));
    lv_label_set_text(ui_LABSettingsDesc, "Settings");
    lv_obj_set_style_text_color(ui_LABSettingsDesc, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABSettingsDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABSettingsDesc, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABConnVer2 = lv_label_create(ui_SCREENSettings);
    lv_obj_set_width(ui_LABConnVer2, lv_pct(94));
    lv_obj_set_height(ui_LABConnVer2, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_LABConnVer2, lv_pct(3));
    lv_obj_set_y(ui_LABConnVer2, lv_pct(-2));
    lv_obj_set_align(ui_LABConnVer2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_LABConnVer2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LABConnVer2, "Software Version 1.0");
    lv_obj_set_style_text_color(ui_LABConnVer2, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LABConnVer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LABConnVer2, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTFactoryReset = lv_btn_create(ui_SCREENSettings);
    lv_obj_set_width(ui_BTFactoryReset, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_BTFactoryReset, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_BTFactoryReset, lv_pct(30));
    lv_obj_set_y(ui_BTFactoryReset, lv_pct(-15));
    lv_obj_set_align(ui_BTFactoryReset, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BTFactoryReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTFactoryReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTFactoryReset, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTFactoryReset, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BTFactoryReset, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BTFactoryReset, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LABFactoryReset = lv_label_create(ui_BTFactoryReset);
    lv_obj_set_width(ui_LABFactoryReset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LABFactoryReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LABFactoryReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LABFactoryReset, "Factory reset");
    lv_obj_set_style_text_font(ui_LABFactoryReset, &ui_font_MicrogrammaSMALL16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SCREENSettings, ui_event_SCREENSettings, LV_EVENT_ALL, NULL);

}
