// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: Helix Control panel 3

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SCREENIdle
void ui_SCREENIdle_screen_init(void);
lv_obj_t * ui_SCREENIdle;
lv_obj_t * ui_LABIdleTime;
lv_obj_t * ui_LABIdleTemp;


// SCREEN: ui_SCREENmain
void ui_SCREENmain_screen_init(void);
void ui_event_SCREENmain(lv_event_t * e);
lv_obj_t * ui_SCREENmain;
lv_obj_t * ui_BTDownTemp;
lv_obj_t * ui_BTUpTemp;
lv_obj_t * ui_LABTime;
lv_obj_t * ui_LABRoomTemp;
lv_obj_t * ui_LABRoomSetpoint;
lv_obj_t * ui_LABRoomHum;
lv_obj_t * ui_LABIndicators;


// SCREEN: ui_SCREENConnections
void ui_SCREENConnections_screen_init(void);
void ui_event_SCREENConnections(lv_event_t * e);
lv_obj_t * ui_SCREENConnections;
lv_obj_t * ui_PANELConnection;
lv_obj_t * ui_IPLab;
lv_obj_t * ui_QR;
lv_obj_t * ui_SWAccessPoint;
lv_obj_t * ui_LABAccessPoint;
lv_obj_t * ui_LABConnectionDesc;
lv_obj_t * ui_LABConnVer;


// SCREEN: ui_SCREENSettings
void ui_SCREENSettings_screen_init(void);
void ui_event_SCREENSettings(lv_event_t * e);
lv_obj_t * ui_SCREENSettings;
lv_obj_t * ui_PANELSettings;
lv_obj_t * ui_SWWebFileManager;
lv_obj_t * ui_LABWebFileManager;
lv_obj_t * ui_SWWebAdvSettings;
lv_obj_t * ui_LABWebAdvSettings;
lv_obj_t * ui_SWWebTerminal;
lv_obj_t * ui_LABWebTerminal;
lv_obj_t * ui_LABSettingsDesc;
lv_obj_t * ui_LABConnVer2;
lv_obj_t * ui_BTFactoryReset;
lv_obj_t * ui_LABFactoryReset;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SCREENmain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SCREENConnections, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SCREENConnections_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SCREENSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_SCREENSettings_screen_init);
    }
}
void ui_event_SCREENConnections(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SCREENmain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_SCREENmain_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SCREENSettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SCREENSettings_screen_init);
    }
}
void ui_event_SCREENSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SCREENConnections, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_SCREENConnections_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SCREENmain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_SCREENmain_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SCREENIdle_screen_init();
    ui_SCREENmain_screen_init();
    ui_SCREENConnections_screen_init();
    ui_SCREENSettings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SCREENIdle);
}
